"""Build 2000-era country leaders (one per ideology group) from tools/data/leaders/. Idempotent.

Data: tools/data/leaders/<region>.csv, one row per country and ideology group:

  tag            country tag
  slot           democratic | communism | fascism | neutrality
  character_id   <TAG>_<first>_<last>, lowercase ascii; reuse an existing mod
                 character's id to keep that character (and its portrait)
  name           display name
  ideology       sub-ideology from common/ideologies (must belong to `slot`)
  party          full name of the real 2000 party for this ideology slot; becomes the
                 in-game party name (set_party_name long_name)
  party_short    its usual abbreviation or short name (in-game short name); blank = derived
  ruling         yes for the person governing on 2000.1.1, else blank
  portrait_url   direct image URL (upload.wikimedia.org preferred), blank = generic portrait
  source         page the portrait/licence comes from
  notes          why this person is the best match

Output (all generated, safe to regenerate):
  common/characters/tnd_<TAG>.txt              character definitions
  gfx/leaders/<TAG>/tnd_<character_id>.dds     156x210 portraits (downloads cached in tools/cache/portraits)
  interface/tnd_leaders.gfx                    portrait sprites
  localisation/english/tnd_leaders_l_english.yml
  history/countries/<TAG> - *.txt              a generated `2000.1.1` block recruiting the four
                                               leaders; older country-leader recruitment is commented out

Usage:
    python tools/build_leaders.py --check      # validate data only
    python tools/build_leaders.py              # download portraits and write everything
"""

from __future__ import annotations

import argparse
import csv
import io
import os
import re
import sys
import time
import urllib.request
from dataclasses import dataclass
from pathlib import Path

import clausewitz as cw
import states as st

REPO = st.REPO_ROOT
DATA = Path(__file__).resolve().parent / "data" / "leaders"
CACHE = Path(__file__).resolve().parent / "cache" / "portraits"
SLOTS = ("democratic", "communism", "fascism", "neutrality")
ID_RE = re.compile(r"^[A-Z0-9]{3}_[a-z0-9_]+$")
BEGIN = "# BEGIN TND leaders (generated by tools/build_leaders.py; edit tools/data/leaders instead)"
END = "# END TND leaders"
PORTRAIT_SIZE = (156, 210)
USER_AGENT = "TND-HOI4-mod-leader-builder/1.0 (https://github.com/ofmon/TND)"


@dataclass
class Leader:
    source: str
    tag: str
    slot: str
    id: str
    name: str
    ideology: str
    party: str
    ruling: bool
    portrait_url: str
    party_short_name: str = ""

    @property
    def short_party(self) -> str:
        return self.party_short_name or party_short(self.party)

    @property
    def sprite(self) -> str:
        return f"GFX_portrait_tnd_{self.id}"

    @property
    def dds(self) -> Path:
        return REPO / "gfx" / "leaders" / self.tag / f"tnd_{self.id}.dds"


def load_rows() -> tuple[list[Leader], list[str]]:
    rows: list[Leader] = []
    errors: list[str] = []
    for path in sorted(DATA.glob("*.csv")):
        with open(path, encoding="utf-8-sig", newline="") as f:
            for n, r in enumerate(csv.DictReader(f), start=2):
                where = f"{path.name}:{n}"
                try:
                    rows.append(Leader(where, r["tag"].strip(), r["slot"].strip(), r["character_id"].strip(),
                                       r["name"].strip(), r["ideology"].strip(), (r.get("party") or "").strip(),
                                       (r.get("ruling") or "").strip().lower() == "yes",
                                       (r.get("portrait_url") or "").strip(),
                                       (r.get("party_short") or "").strip()))
                except (KeyError, AttributeError) as exc:
                    errors.append(f"{where}: bad row ({exc!r})")
    return rows, errors


def ideology_groups() -> dict[str, str]:
    """sub-ideology -> ideology group, from the mod's ideologies (falling back to vanilla names)."""
    groups: dict[str, str] = {}
    for path in (REPO / "common" / "ideologies").glob("*.txt"):
        for top in cw.parse_file(path):
            if top.key != "ideologies" or not top.is_block:
                continue
            for group in top.value:  # type: ignore[union-attr]
                types = cw.first(group.value, "types") if group.is_block else None  # type: ignore[arg-type]
                if types is not None and types.is_block:
                    for t in types.value:  # type: ignore[union-attr]
                        if t.key:
                            groups[t.key] = group.key  # type: ignore[assignment]
    return groups


def existing_characters() -> dict[str, tuple[Path, bool]]:
    """Mod characters not generated by this script: id -> (file, has a country_leader role)."""
    found: dict[str, tuple[Path, bool]] = {}
    for path in (REPO / "common" / "characters").glob("*.txt"):
        if path.name.startswith("tnd_"):
            continue
        try:
            entries = cw.parse_file(path)
        except cw.ParseError:
            continue
        for top in entries:
            if top.key == "characters" and top.is_block:
                for c in top.value:  # type: ignore[union-attr]
                    if c.key and c.is_block:
                        found[c.key] = (path, cw.first(c.value, "country_leader") is not None)  # type: ignore[arg-type]
    return found


def history_files(tag: str) -> list[Path]:
    """Every history file the game loads for `tag` (with a capital), in load order.

    HOI4 applies all of them, so duplicates (e.g. a copy whose name differs by a
    space) all matter; the last one loaded wins.
    """
    files = []
    for p in sorted((REPO / "history" / "countries").glob(f"{tag} - *.txt")):
        try:
            if cw.first(cw.parse_file(p), "capital") is not None:
                files.append(p)
        except cw.ParseError:
            continue
    return files


def history_file(tag: str) -> Path | None:
    files = history_files(tag)
    return files[-1] if files else None


def strip_generated(text: str) -> str:
    return re.sub(rf"\n*{re.escape(BEGIN)}.*?{re.escape(END)}\n?", "\n", text, flags=re.S)


def politics(path: Path, text: str | None = None) -> dict[str, str]:
    """Effective set_politics fields on the start date (later blocks override), ignoring our block."""
    try:
        entries = cw.parse(strip_generated(text if text is not None else cw.read_text(path)))
    except cw.ParseError:
        return {}
    found: dict[str, str] = {}

    def take(block: list[cw.Entry]) -> None:
        for f in block:
            if f.key and not f.is_block:
                found[f.key] = f.value  # type: ignore[assignment]

    undated = [e for e in entries if e.key == "set_politics" and e.is_block]
    for e in undated:
        take(e.value)  # type: ignore[arg-type]
    dated = sorted((st.parse_date(e.key), i, e) for i, e in enumerate(entries)
                   if e.is_block and st.parse_date(e.key) and st.parse_date(e.key) <= st.START_DATE)
    for _, _, d in dated:
        for e in d.value:  # type: ignore[union-attr]
            if e.key == "set_politics" and e.is_block:
                take(e.value)  # type: ignore[arg-type]
    return found


def ruling_group(path: Path, text: str | None = None) -> str | None:
    return politics(path, text).get("ruling_party")


def next_valid_election(last: str | None, months: int) -> str | None:
    """Roll an overdue last_election forward by whole cycles so the next one is after the start date."""
    d = st.parse_date(last) if last else None
    if d is None or months <= 0:
        return None
    y, m, day = d
    day = min(day, 28)  # every month has it
    changed = False
    while True:
        nm = m + months
        ny, nm = y + (nm - 1) // 12, (nm - 1) % 12 + 1
        if (ny, nm, day) > st.START_DATE:
            break
        y, m = ny, nm
        changed = True
    return f"{y}.{m}.{day}" if changed else None


def check(rows: list[Leader], groups: dict[str, str], chars: dict[str, tuple[Path, bool]]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    tags = st.defined_tags()
    seen_ids: dict[str, str] = {}
    by_tag: dict[str, dict[str, Leader]] = {}
    for r in rows:
        if r.tag not in tags:
            errors.append(f"{r.source}: {r.tag} is not a defined tag")
        if r.slot not in SLOTS:
            errors.append(f"{r.source}: slot must be one of {SLOTS}, not {r.slot!r}")
        if r.id not in chars and (not ID_RE.match(r.id) or not r.id.startswith(r.tag + "_")):
            errors.append(f"{r.source}: character_id {r.id!r} must look like {r.tag}_first_last (lowercase)")
        if not r.id.isascii():
            # the id is also its localisation key, and one non-ASCII key stops HOI4
            # reading the rest of the localisation file
            errors.append(f"{r.source}: character_id {r.id!r} must be ASCII (use a new ascii id)")
        if r.id in seen_ids:
            errors.append(f"{r.source}: character_id {r.id} also used at {seen_ids[r.id]}")
        seen_ids[r.id] = r.source
        if groups.get(r.ideology) != r.slot:
            errors.append(f"{r.source}: ideology {r.ideology!r} is not a {r.slot} sub-ideology "
                          f"(valid: {', '.join(sorted(k for k, v in groups.items() if v == r.slot))})")
        if not r.name:
            errors.append(f"{r.source}: name is required")
        if r.portrait_url and not r.portrait_url.startswith("https://"):
            errors.append(f"{r.source}: portrait_url must be an https URL")
        if r.slot in by_tag.setdefault(r.tag, {}):
            errors.append(f"{r.source}: {r.tag} already has a {r.slot} leader")
        by_tag[r.tag][r.slot] = r
    owners = {s.owner for s in st.load_all() if s.owner}
    for tag in sorted(owners - set(by_tag)):
        warnings.append(f"{tag}: no leaders in data/leaders")
    for tag, slots in sorted(by_tag.items()):
        missing = [s for s in SLOTS if s not in slots]
        if missing:
            warnings.append(f"{tag}: missing {', '.join(missing)} leader")
        ruling = [r for r in slots.values() if r.ruling]
        if len(ruling) != 1:
            errors.append(f"{tag}: exactly one leader must have ruling=yes (found {len(ruling)})")
        hist = history_file(tag)
        if hist is None:
            warnings.append(f"{tag}: no history/countries file; leaders will be defined but not recruited")
        elif ruling and ruling_group(hist) != ruling[0].slot:
            print(f"note: {tag}: {hist.name} sets ruling_party = {ruling_group(hist)}; "
                  f"the generated block switches it to {ruling[0].slot}")
    return errors, warnings


def fetch(url: str) -> bytes:
    CACHE.mkdir(parents=True, exist_ok=True)
    key = re.sub(r"[^A-Za-z0-9._-]", "_", url.split("//", 1)[1])[-150:]
    cached = CACHE / key
    if cached.exists():
        return cached.read_bytes()
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    for attempt in range(4):
        try:
            with urllib.request.urlopen(req, timeout=60) as resp:
                data = resp.read()
            cached.write_bytes(data)
            time.sleep(0.5)  # be polite to Wikimedia
            return data
        except Exception:  # noqa: BLE001 - retried, then re-raised
            if attempt == 3:
                raise
            time.sleep(2 ** attempt * 2)
    raise RuntimeError("unreachable")


def make_portrait(data: bytes, out: Path) -> None:
    """Crop to the portrait aspect ratio (keeping the top, where the face is) and save as DDS."""
    from PIL import Image, ImageOps

    im = ImageOps.exif_transpose(Image.open(io.BytesIO(data))).convert("RGB")
    tw, th = PORTRAIT_SIZE
    w, h = im.size
    target = tw / th
    if w / h > target:  # too wide: crop the sides evenly
        nw = round(h * target)
        im = im.crop(((w - nw) // 2, 0, (w - nw) // 2 + nw, h))
    else:  # too tall: keep head and shoulders
        nh = round(w / target)
        top = min(round(h * 0.05), h - nh)
        im = im.crop((0, top, w, top + nh))
    im = im.resize(PORTRAIT_SIZE, Image.LANCZOS).convert("RGBA")
    out.parent.mkdir(parents=True, exist_ok=True)
    buf = io.BytesIO()
    im.save(buf, format="DDS")
    out.write_bytes(normalise_dds_header(buf.getvalue()))


def normalise_dds_header(data: bytes) -> bytes:
    """Match the header of the mod's working portraits: one mip level, depth 1, MIPMAPCOUNT flag set."""
    import struct

    header = bytearray(data[:128])
    flags = struct.unpack_from("<I", header, 8)[0] | 0x20000  # DDSD_MIPMAPCOUNT
    struct.pack_into("<I", header, 8, flags)
    struct.pack_into("<I", header, 24, 1)  # depth
    struct.pack_into("<I", header, 28, 1)  # mip map count
    return bytes(header) + data[128:]


def character_block(r: Leader, has_portrait: bool) -> str:
    lines = [f"\t{r.id} = {{", f"\t\tname = {r.id}"]
    if has_portrait:
        lines += ["\t\tportraits = {", "\t\t\tcivilian = {", f"\t\t\t\tlarge = {r.sprite}", "\t\t\t}", "\t\t}"]
    lines += ["\t\tcountry_leader = {", f"\t\t\tideology = {r.ideology}", '\t\t\texpire = "2050.1.1.1"',
              "\t\t\tid = -1", "\t\t}", "\t}"]
    return "\n".join(lines)


def comment_out(text: str, spans: list[tuple[int, int]]) -> str:
    """Prefix every line touched by the given spans with '#'."""
    lines = text.split("\n")
    offsets, pos = [], 0
    for line in lines:
        offsets.append(pos)
        pos += len(line) + 1
    marked: set[int] = set()
    for start, end in spans:
        for i, off in enumerate(offsets):
            if off <= end and off + len(lines[i]) >= start:
                marked.add(i)
    return "\n".join(("#" + l if i in marked and not l.lstrip().startswith("#") else l) for i, l in enumerate(lines))


def update_history(path: Path, leaders: list[Leader], chars: dict[str, tuple[Path, bool]],
                   generate: bool, pol: dict[str, str]) -> bool:
    """Disable older country-leader setup in `path`; append the generated block when `generate`.

    `pol` is the tag's effective set_politics across all its history files.
    """
    text = cw.read_text(path).replace("\r\n", "\n")
    text = strip_generated(text)
    keep = {r.id for r in leaders}
    try:
        entries = cw.parse(text)
    except cw.ParseError as exc:
        print(f"WARNING: {path.name}: {exc}; leaders appended without disabling older ones")
        entries = []
    spans: list[tuple[int, int]] = []

    def scan(es: list[cw.Entry]) -> None:
        for e in es:
            if e.key == "create_country_leader":
                spans.append((e.start, e.end))
            elif e.key == "recruit_character" and not e.is_block:
                known = chars.get(e.value)  # type: ignore[arg-type]
                # our leaders are recruited only by the generated block; drop other
                # country leaders and ids that no longer exist
                if e.value in keep or known is None or known[1]:
                    spans.append((e.start, e.end))
            elif e.is_block:
                scan(e.value)  # type: ignore[arg-type]
    scan(entries)
    new = comment_out(text, spans).rstrip("\n")
    if generate:
        order = sorted(leaders, key=lambda r: r.ruling)  # ruling leader recruited last
        ruler = next((r for r in leaders if r.ruling), None)
        fields = []
        if ruler is not None and ruler.slot != pol.get("ruling_party"):
            fields.append(f"ruling_party = {ruler.slot}")  # the data's ruler governs on the start date
        try:
            months = int(float(pol.get("election_frequency", "0")))
        except ValueError:
            months = 0
        rolled = next_valid_election(pol.get("last_election"), months)
        if rolled:
            # a 1930s last_election makes the game hold an election on day one and replace the leader
            fields.append(f'last_election = "{rolled}"')
        block = [BEGIN, "2000.1.1 = {"]
        if fields:
            if ruler is not None and f"ruling_party = {ruler.slot}" not in fields:
                fields.insert(0, f"ruling_party = {ruler.slot}")
            block.append("\tset_politics = { " + " ".join(fields) + " }")
        for r in leaders:  # real 2000 party names instead of the 1936 ones
            if r.party:
                key = f"TND_PARTY_{r.tag}_{r.slot}"
                block.append(f"\tset_party_name = {{ ideology = {r.slot} long_name = {key}_long name = {key} }}")
        block += [f"\trecruit_character = {r.id}" for r in order] + ["}", END]
        new += "\n\n" + "\n".join(block) + "\n"
    else:
        new += "\n"
    old = cw.read_text(path).replace("\r\n", "\n")
    if new != old:
        path.write_text(new, encoding="utf-8", newline="\n")
        return True
    return False


def localised_keys(hoi4: Path | None) -> set[str]:
    """Keys already localised by the mod (except our generated file) or vanilla English."""
    keys: set[str] = set()
    roots = [REPO / "localisation"] + ([hoi4 / "localisation" / "english"] if hoi4 else [])
    rx = re.compile(r"^\s*([A-Za-z0-9_.\-À-ɏ]+):\d*\s*\"", re.M)
    for root in roots:
        for p in root.rglob("*.yml"):
            if p.name == "tnd_leaders_l_english.yml":
                continue
            keys.update(rx.findall(p.read_text(encoding="utf-8-sig", errors="replace")))
    return keys


def party_short(party: str) -> str:
    """'Hungarian Justice and Life Party (MIÉP)' -> 'MIÉP'; otherwise the name without notes."""
    m = re.search(r"\(([^()]{2,12})\)\s*$", party)
    if m and re.fullmatch(r"[A-ZÀ-Ý0-9\-–'&. ]+", m.group(1)):
        return m.group(1)
    return re.sub(r"\s*\([^)]*\)\s*$", "", party).strip()


def working_sprites() -> set[str]:
    """Sprites defined in the mod's hand-made .gfx files whose texture file exists."""
    ok: set[str] = set()
    for gfx in (REPO / "interface").glob("*.gfx"):
        if gfx.name == "tnd_leaders.gfx":
            continue
        text = cw.read_text(gfx)
        for m in re.finditer(r'name\s*=\s*"([^"]+)"\s*texturefile\s*=\s*"([^"]+)"', text):
            if (REPO / m.group(2)).exists():
                ok.add(m.group(1))
    return ok


def wikipedia_image(name: str) -> str | None:
    """The lead image of the person's English Wikipedia article, if it has one."""
    import json
    import urllib.parse

    url = ("https://en.wikipedia.org/w/api.php?action=query&prop=pageimages&piprop=original"
           f"&redirects=1&format=json&titles={urllib.parse.quote(name)}")
    try:
        pages = json.loads(fetch(url))["query"]["pages"]
    except Exception:  # noqa: BLE001 - no image is an acceptable outcome
        return None
    for page in pages.values():
        src = page.get("original", {}).get("source")
        if src and not src.lower().endswith((".svg", ".gif")):
            return src
    return None


def ensure_reused_portrait(r: Leader, path: Path, sprites: set[str], no_download: bool) -> bool:
    """Give a reused character our portrait when its own sprite doesn't resolve."""
    text = cw.read_text(path).replace("\r\n", "\n")
    for top in cw.parse(text):
        if top.key != "characters" or not top.is_block:
            continue
        for c in top.value:  # type: ignore[union-attr]
            if c.key != r.id or not c.is_block:
                continue
            portraits = cw.first(c.value, "portraits")  # type: ignore[arg-type]
            large = None
            if portraits is not None and portraits.is_block:
                for kind in portraits.value:  # type: ignore[union-attr]
                    if kind.is_block:
                        large = large or cw.scalar(kind.value, "large")  # type: ignore[arg-type]
            if large in sprites:
                return False
            if large == r.sprite and r.dds.exists():
                return True  # already repointed by an earlier run
            url = r.portrait_url or wikipedia_image(r.name)
            if not url:
                return False
            if not (r.dds.exists() and no_download):
                make_portrait(fetch(url), r.dds)
            block = f"portraits = {{\n\t\t\tcivilian = {{\n\t\t\t\tlarge = {r.sprite}\n\t\t\t}}\n\t\t}}"
            if portraits is not None:
                new = text[:portraits.start] + block + text[portraits.end:]
            else:
                name_e = cw.first(c.value, "name")  # type: ignore[arg-type]
                at = name_e.end if name_e is not None else c.value_start + 1
                new = text[:at] + "\n\t\t" + block + text[at:]
            path.write_text(new, encoding="utf-8", newline="\n")
            print(f"{path.name}: {r.id} portrait {large} missing -> {r.sprite}")
            return True
    return False


def sync_reused_ideology(r: Leader, path: Path) -> bool:
    """Make a reused hand-made character's country_leader ideology match the data row."""
    text = cw.read_text(path).replace("\r\n", "\n")
    for top in cw.parse(text):
        if top.key != "characters" or not top.is_block:
            continue
        for c in top.value:  # type: ignore[union-attr]
            if c.key != r.id or not c.is_block:
                continue
            role = cw.first(c.value, "country_leader")  # type: ignore[arg-type]
            ideo = cw.first(role.value, "ideology") if role is not None and role.is_block else None  # type: ignore[arg-type]
            if ideo is None or ideo.value == r.ideology:
                return False
            new = text[:ideo.value_start] + r.ideology + text[ideo.value_end:]
            path.write_text(new, encoding="utf-8", newline="\n")
            print(f"{path.name}: {r.id} ideology {ideo.value} -> {r.ideology}")
            return True
    return False


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--no-download", action="store_true", help="use cached portraits only")
    args = ap.parse_args()

    rows, errors = load_rows()
    groups = ideology_groups()
    chars = existing_characters()
    if not errors:
        e2, warnings = check(rows, groups, chars)
        errors += e2
        for w in warnings:
            print(f"WARNING: {w}")
    if errors:
        print("\n".join(f"ERROR: {e}" for e in errors))
        return 1
    print(f"data OK: {len(rows)} leaders for {len({r.tag for r in rows})} countries")
    if args.check:
        return 0

    by_tag: dict[str, list[Leader]] = {}
    for r in rows:
        by_tag.setdefault(r.tag, []).append(r)

    sprites = working_sprites()
    sprites_out: list[str] = []
    loc = ["l_english:"]
    known_loc = localised_keys(Path(os.environ["HOI4_PATH"]) if os.environ.get("HOI4_PATH") else None)
    failed: list[str] = []

    def q(s: str) -> str:
        return s.replace('"', "'")

    for tag, leaders in sorted(by_tag.items()):
        blocks = []
        for r in leaders:
            if r.party:
                key = f"TND_PARTY_{r.tag}_{r.slot}"
                loc.append(f' {key}:0 "{q(r.short_party)}"')
                loc.append(f' {key}_long:0 "{q(r.party)}"')
            if r.id in chars:  # reuse a hand-made character, aligning its ideology and portrait
                if r.id not in known_loc:  # hand-made characters often lack a name key
                    loc.append(f' {r.id}:0 "{q(r.name)}"')
                sync_reused_ideology(r, chars[r.id][0])
                try:
                    if ensure_reused_portrait(r, chars[r.id][0], sprites, args.no_download):
                        rel = r.dds.relative_to(REPO).as_posix()
                        sprites_out.append(f'\tspriteType = {{\n\t\tname = "{r.sprite}"\n\t\ttexturefile = "{rel}"\n\t}}')
                except Exception as exc:  # noqa: BLE001 - reported below
                    failed.append(f"{r.source} {r.id}: {exc}")
                continue
            has_portrait = False
            if r.portrait_url:
                try:
                    if not r.dds.exists() or not args.no_download:
                        make_portrait(fetch(r.portrait_url), r.dds)
                    has_portrait = True
                except Exception as exc:  # noqa: BLE001 - reported, generic portrait used instead
                    failed.append(f"{r.source} {r.id}: {exc}")
                    has_portrait = r.dds.exists()
            if has_portrait:
                rel = r.dds.relative_to(REPO).as_posix()
                sprites_out.append(f'\tspriteType = {{\n\t\tname = "{r.sprite}"\n\t\ttexturefile = "{rel}"\n\t}}')
            blocks.append(character_block(r, has_portrait))
            loc.append(f' {r.id}:0 "{r.name.replace(chr(34), chr(39))}"')
        out = REPO / "common" / "characters" / f"tnd_{tag}.txt"
        if blocks:
            out.write_text("characters = {\n" + "\n".join(blocks) + "\n}\n", encoding="utf-8", newline="\n")
        files = history_files(tag)
        pol: dict[str, str] = {}
        for f in files:
            pol.update(politics(f))
        for i, f in enumerate(files):
            update_history(f, leaders, chars, generate=i == len(files) - 1, pol=pol)
        if len(files) > 1:
            print(f"WARNING: {tag} has {len(files)} history files that all load: "
                  f"{', '.join(repr(f.name) for f in files)}; remove the stale one")

    (REPO / "interface" / "tnd_leaders.gfx").write_text(
        "spriteTypes = {\n" + "\n".join(sprites_out) + "\n}\n", encoding="utf-8", newline="\n")
    # HOI4 requires UTF-8 with BOM for localisation
    (REPO / "localisation" / "english" / "tnd_leaders_l_english.yml").write_text(
        "\n".join(loc) + "\n", encoding="utf-8-sig", newline="\n")
    for f in failed:
        print(f"WARNING: portrait failed, generic used: {f}")
    print(f"wrote leaders for {len(by_tag)} countries, {len(sprites_out)} portraits")
    return 0


if __name__ == "__main__":
    sys.exit(main())
