"""Localisation layer: modern (1 Jan 2000) names for states and victory points.

Vanilla names reflect 1936 (Hsinking, Königsberg, Leningrad, Batavia ...). The
curated renames in tools/data/modern_names/*.csv (``key,name,rationale``, where key
is ``STATE_<id>`` or ``VICTORY_POINTS_<province>``) are generated into
localisation/replace/tnd_modern_names_l_english.yml, which overrides both vanilla
and the mod's other localisation key by key.

Usage:
    python tools/build_modern_names.py            # build the localisation file
    python tools/build_modern_names.py --export   # write tools/cache/current_names.csv
                                                  # (every name currently in effect, for research)
"""

from __future__ import annotations

import argparse
import csv
import os
import re
import sys
from pathlib import Path

import province_geo
import states as st

DATA = Path(__file__).resolve().parent / "data" / "modern_names"
OUT = st.REPO_ROOT / "localisation" / "replace" / "tnd_modern_names_l_english.yml"
EXPORT = Path(__file__).resolve().parent / "cache" / "current_names.csv"
_LINE = re.compile(r'^\s*((?:STATE|VICTORY_POINTS)_\d+)\s*:\s*\d*\s*"(.*)"\s*(?:#.*)?$')
_KEY = re.compile(r"^(STATE|VICTORY_POINTS)_\d+$")


def read_loc(paths: list[Path]) -> dict[str, str]:
    names: dict[str, str] = {}
    for p in paths:
        for line in p.read_text(encoding="utf-8-sig", errors="replace").splitlines():
            m = _LINE.match(line)
            if m:
                names[m.group(1)] = m.group(2)
    return names


def current_names(hoi4: Path) -> dict[str, str]:
    """Names in effect: vanilla, overridden by the mod (excluding this generator's output)."""
    vanilla = read_loc(sorted((hoi4 / "localisation" / "english").glob("*.yml")))
    mod_files = [p for p in sorted((st.REPO_ROOT / "localisation").rglob("*_l_english.yml")) if p != OUT]
    return {**vanilla, **read_loc(mod_files)}


def export(hoi4: Path) -> None:
    names = current_names(hoi4)
    geo = province_geo.load(hoi4)
    EXPORT.parent.mkdir(exist_ok=True)
    with open(EXPORT, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["key", "current_name", "state", "owner", "lat", "lon"])
        for s in sorted(st.load_all(), key=lambda s: s.id):
            lat = sum(geo[p]["lat"] for p in s.provinces) / len(s.provinces)
            lon = sum(geo[p]["lon"] for p in s.provinces) / len(s.provinces)
            w.writerow([f"STATE_{s.id}", names.get(f"STATE_{s.id}", ""), s.id, s.owner, round(lat, 2), round(lon, 2)])
            for p in sorted(s.victory_points):
                g = geo.get(p, {})
                w.writerow([f"VICTORY_POINTS_{p}", names.get(f"VICTORY_POINTS_{p}", ""), s.id, s.owner, g.get("lat"), g.get("lon")])
    print(f"wrote {EXPORT}")


def build() -> int:
    rows = []
    errors = []
    seen: dict[str, str] = {}
    for path in sorted(DATA.glob("*.csv")):
        with open(path, encoding="utf-8-sig", newline="") as f:
            for n, r in enumerate(csv.DictReader(f), start=2):
                where = f"{path.name}:{n}"
                key, name = (r.get("key") or "").strip(), (r.get("name") or "").strip()
                if not _KEY.match(key):
                    errors.append(f"{where}: bad key {key!r}")
                if not name or '"' in name:
                    errors.append(f"{where}: name must be non-empty and contain no double quotes")
                if key in seen:
                    errors.append(f"{where}: {key} already renamed at {seen[key]}")
                seen[key] = where
                rows.append((key, name))
    if errors:
        print("\n".join(f"ERROR: {e}" for e in errors))
        return 1
    lines = ["l_english:", " # GENERATED by tools/build_modern_names.py from tools/data/modern_names/ - do not edit."]
    lines += [f' {k}:0 "{v}"' for k, v in rows]
    # HOI4 requires UTF-8 with BOM for localisation
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8-sig", newline="\n")
    print(f"{len(rows)} modern names written to {OUT.relative_to(st.REPO_ROOT)}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--hoi4", type=Path, default=os.environ.get("HOI4_PATH"))
    ap.add_argument("--export", action="store_true")
    args = ap.parse_args()
    if args.export:
        if args.hoi4 is None:
            print("ERROR: --export needs --hoi4 / HOI4_PATH")
            return 1
        export(args.hoi4)
        return 0
    return build()


if __name__ == "__main__":
    sys.exit(main())
