"""Generate the mod's formable-nation decisions from tools/data/formables.json.

Outputs (all fully regenerated - edit the JSON, not these):
  common/decisions/tnd_formables.txt
  common/decisions/categories/tnd_formables_categories.txt
  localisation/english/tnd_formables_l_english.yml
  gfx/flags/{,medium/,small/}<cosmetic_tag>[_<ideology>].tga   (placeholder flags)

Each formable follows vanilla's pattern (see formable_nation_decisions.txt):
a decision that requires controlling every listed state, then applies a
cosmetic tag, cores the listed states for ROOT and sets a global flag so the
nation can only be formed once per game.

Spec format (tools/data/formables.json) - one object per formable:
  id           lowercase key; the cosmetic tag is ``tnd_<id>``
  name         display name; optional ``names`` {ideology: name} overrides it
  def / adj    "the Soviet Union" / "Soviet"; optional ``defs`` {ideology: def}
  allowed      original tags that may form it
  components   [{label, states: [ids]}] - required states, grouped for the tooltip
  extra_cores  optional [ids] cored on formation but not required
  ideology     optional; the former must have this government
  description  decision description text
  flag         {stripes: "horizontal"|"vertical", colors: [...], ratios?: [...],
                emblems?: [{shape, color, x, y, size, ...}]}
               shapes: star, circle, crescent, nordic_cross, hoist_triangle, canton

Usage:
    python tools/build_formables.py
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

from PIL import Image, ImageDraw

import states as st

REPO = st.REPO_ROOT
SPEC = Path(__file__).resolve().parent / "data" / "formables.json"
DECISIONS = REPO / "common" / "decisions" / "tnd_formables.txt"
CATEGORIES = REPO / "common" / "decisions" / "categories" / "tnd_formables_categories.txt"
LOC = REPO / "localisation" / "english" / "tnd_formables_l_english.yml"
FLAG_DIRS = {REPO / "gfx" / "flags": (82, 52), REPO / "gfx" / "flags" / "medium": (41, 26), REPO / "gfx" / "flags" / "small": (10, 7)}
IDEOLOGIES = ("democratic", "communism", "fascism", "neutrality")
CATEGORY = "tnd_formable_nations"
HEADER = "# GENERATED by tools/build_formables.py from tools/data/formables.json - do not edit.\n"


# --- validation ----------------------------------------------------------------

def validate(spec: list[dict], state_ids: set[int], tags: set[str]) -> list[str]:
    errors = []
    seen = set()
    for f in spec:
        fid = f.get("id", "?")
        if fid in seen:
            errors.append(f"{fid}: duplicate id")
        seen.add(fid)
        if not fid.replace("_", "").isalnum() or fid != fid.lower():
            errors.append(f"{fid}: id must be lowercase letters/digits/underscores")
        for key in ("name", "def", "adj", "allowed", "components", "description", "flag"):
            if key not in f:
                errors.append(f"{fid}: missing {key!r}")
        for t in f.get("allowed", []):
            if t not in tags:
                errors.append(f"{fid}: allowed tag {t} is not defined")
        if f.get("ideology") and f["ideology"] not in IDEOLOGIES:
            errors.append(f"{fid}: unknown ideology {f['ideology']!r}")
        all_states = [s for c in f.get("components", []) for s in c["states"]] + f.get("extra_cores", [])
        for s in all_states:
            if s not in state_ids:
                errors.append(f"{fid}: state {s} does not exist")
        if len(all_states) != len(set(all_states)):
            errors.append(f"{fid}: a state is listed twice")
    return errors


# --- decisions -----------------------------------------------------------------

def _or_tags(tags: list[str], indent: str) -> str:
    inner = "".join(f"{indent}\toriginal_tag = {t}\n" for t in tags)
    return f"{indent}OR = {{\n{inner}{indent}}}\n"


def decision(f: dict) -> str:
    fid = f["id"]
    key = f"form_tnd_{fid}"
    flag = f"tnd_{fid}_formed"
    ind = "\t\t"
    out = [f"\t{key} = {{\n", "\t\ticon = generic_form_nation\n\n"]
    out.append(f"{ind}allowed = {{\n{_or_tags(f['allowed'], ind + chr(9))}{ind}}}\n\n")
    vis = _or_tags(f["allowed"], ind + "\t") + f"{ind}\tNOT = {{ has_global_flag = {flag} }}\n"
    out.append(f"{ind}visible = {{\n{vis}{ind}}}\n\n")
    out.append(f"{ind}available = {{\n{ind}\tis_subject = no\n")
    if f.get("ideology"):
        out.append(f"{ind}\thas_government = {f['ideology']}\n")
    for i, comp in enumerate(f["components"]):
        states = "".join(f"{ind}\t\tcontrols_state = {s}\n" for s in comp["states"])
        out.append(f"{ind}\tcustom_trigger_tooltip = {{\n{ind}\t\ttooltip = {key}_req_{i}_tt\n{states}{ind}\t}}\n")
    out.append(f"{ind}}}\n\n")
    cored = [s for c in f["components"] for s in c["states"]] + f.get("extra_cores", [])
    limit = "".join(f"{ind}\t\t\t\t\tstate = {s}\n" for s in cored)
    out.append(
        f"{ind}complete_effect = {{\n"
        f"{ind}\tset_cosmetic_tag = tnd_{fid}\n"
        f"{ind}\tset_global_flag = {flag}\n"
        f"{ind}\tcustom_effect_tooltip = {key}_cores_tt\n"
        f"{ind}\thidden_effect = {{\n"
        f"{ind}\t\tevery_state = {{\n"
        f"{ind}\t\t\tlimit = {{\n{ind}\t\t\t\tOR = {{\n{limit}{ind}\t\t\t\t}}\n{ind}\t\t\t}}\n"
        f"{ind}\t\t\tadd_core_of = ROOT\n"
        f"{ind}\t\t}}\n"
        f"{ind}\t}}\n"
        f"{ind}}}\n\n"
    )
    out.append(f"{ind}ai_will_do = {{\n{ind}\tfactor = 100\n{ind}}}\n\t}}\n")
    return "".join(out)


def write_decisions(spec: list[dict]) -> None:
    DECISIONS.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(decision(f) for f in spec)
    DECISIONS.write_text(f"{HEADER}\n{CATEGORY} = {{\n{body}}}\n", encoding="utf-8", newline="\n")
    CATEGORIES.parent.mkdir(parents=True, exist_ok=True)
    CATEGORIES.write_text(
        f"{HEADER}\n{CATEGORY} = {{\n\ticon = generic_formable_nations\n\tpriority = 50\n}}\n",
        encoding="utf-8",
        newline="\n",
    )


# --- localisation --------------------------------------------------------------

def _q(text: str) -> str:
    return text.replace('"', "'")


def write_loc(spec: list[dict]) -> None:
    lines = ["l_english:", f" {HEADER.strip()}", f' {CATEGORY}:0 "Formable Nations"']
    for f in spec:
        fid, key, tag = f["id"], f"form_tnd_{f['id']}", f"tnd_{f['id']}"
        names, defs = f.get("names", {}), f.get("defs", {})
        lines += [
            "",
            f' {key}:0 "Proclaim {_q(f["def"])}"',
            f' {key}_desc:0 "{_q(f["description"])}"',
            f' {key}_cores_tt:0 "Gain §Ycores§! on every state of {_q(f["def"])}."',
        ]
        for i, comp in enumerate(f["components"]):
            lines.append(f' {key}_req_{i}_tt:0 "Controls all states of §Y{_q(comp["label"])}§!"')
        lines += [f' {tag}:0 "{_q(f["name"])}"', f' {tag}_DEF:0 "{_q(f["def"])}"', f' {tag}_ADJ:0 "{_q(f["adj"])}"']
        for ideo in IDEOLOGIES:
            lines += [
                f' {tag}_{ideo}:0 "{_q(names.get(ideo, f["name"]))}"',
                f' {tag}_{ideo}_DEF:0 "{_q(defs.get(ideo, f["def"]))}"',
                f' {tag}_{ideo}_ADJ:0 "{_q(f["adj"])}"',
            ]
    LOC.parent.mkdir(parents=True, exist_ok=True)
    LOC.write_text("\n".join(lines) + "\n", encoding="utf-8-sig", newline="\n")


# --- flags ---------------------------------------------------------------------

SCALE = 8  # supersample for antialiasing


def _rgb(c: str) -> tuple[int, int, int, int]:
    c = c.lstrip("#")
    return (int(c[0:2], 16), int(c[2:4], 16), int(c[4:6], 16), 255)


def _star(cx: float, cy: float, r: float, points: int = 5) -> list[tuple[float, float]]:
    pts = []
    for i in range(points * 2):
        rad = r if i % 2 == 0 else r * 0.382
        ang = -math.pi / 2 + i * math.pi / points
        pts.append((cx + rad * math.cos(ang), cy + rad * math.sin(ang)))
    return pts


def render_flag(spec: dict, w: int = 82, h: int = 52) -> Image.Image:
    W, H = w * SCALE, h * SCALE
    img = Image.new("RGBA", (W, H))
    d = ImageDraw.Draw(img)
    colors = [_rgb(c) for c in spec["colors"]]
    ratios = spec.get("ratios") or [1] * len(colors)
    total = sum(ratios)
    pos = 0.0
    for col, r in zip(colors, ratios):
        span = r / total
        if spec.get("stripes", "horizontal") == "horizontal":
            d.rectangle([0, pos * H, W, (pos + span) * H], fill=col)
        else:
            d.rectangle([pos * W, 0, (pos + span) * W, H], fill=col)
        pos += span
    for e in spec.get("emblems", []):
        col = _rgb(e["color"])
        cx, cy, size = e.get("x", 0.5) * W, e.get("y", 0.5) * H, e.get("size", 0.3) * H
        shape = e["shape"]
        if shape == "star":
            d.polygon(_star(cx, cy, size / 2), fill=col)
        elif shape == "circle":
            d.ellipse([cx - size / 2, cy - size / 2, cx + size / 2, cy + size / 2], fill=col)
        elif shape == "crescent":
            bg = _rgb(e["background"])
            d.ellipse([cx - size / 2, cy - size / 2, cx + size / 2, cy + size / 2], fill=col)
            off = size * 0.22
            inner = size * 0.8
            d.ellipse([cx - inner / 2 + off, cy - inner / 2, cx + inner / 2 + off, cy + inner / 2], fill=bg)
        elif shape == "nordic_cross":
            t = e.get("thickness", 0.2) * H
            vx = e.get("x", 0.36) * W
            d.rectangle([0, H / 2 - t / 2, W, H / 2 + t / 2], fill=col)
            d.rectangle([vx - t / 2, 0, vx + t / 2, H], fill=col)
        elif shape == "hoist_triangle":
            d.polygon([(0, 0), (e.get("depth", 0.5) * W, H / 2), (0, H)], fill=col)
        elif shape == "canton":
            d.rectangle([0, 0, e.get("width", 0.4) * W, e.get("height", 0.5) * H], fill=col)
        else:
            raise ValueError(f"unknown flag shape {shape!r}")
    return img.resize((w, h), Image.LANCZOS)


def write_flags(spec: list[dict]) -> int:
    # remove flags of formables no longer in the spec (only our generated tnd_ files)
    wanted = {f"tnd_{f['id']}" for f in spec}
    for directory in FLAG_DIRS:
        for old in directory.glob("tnd_*.tga"):
            stem = old.stem
            for ideo in IDEOLOGIES:
                stem = stem.removesuffix(f"_{ideo}")
            if stem not in wanted:
                old.unlink()
    n = 0
    for f in spec:
        base = render_flag(f["flag"])
        for directory, (w, h) in FLAG_DIRS.items():
            directory.mkdir(parents=True, exist_ok=True)
            img = base if (w, h) == base.size else render_flag(f["flag"], w, h)
            # same filename for base and every ideology, as vanilla does for cosmetic tags
            for suffix in ("",) + tuple(f"_{i}" for i in IDEOLOGIES):
                img.save(directory / f"tnd_{f['id']}{suffix}.tga", format="TGA", rle=False)
                n += 1
    return n


def main() -> int:
    # utf-8-sig: tolerate a BOM added by Windows editors
    spec = json.loads(SPEC.read_text(encoding="utf-8-sig"))["formables"]
    state_ids = {s.id for s in st.load_all()}
    errors = validate(spec, state_ids, st.defined_tags())
    if errors:
        print("\n".join(f"ERROR: {e}" for e in errors))
        return 1
    write_decisions(spec)
    write_loc(spec)
    n = write_flags(spec)
    print(f"{len(spec)} formables: decisions, categories, localisation and {n} flag files written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
